/**
* Chat service
* Chat service
*
* The version of the OpenAPI document: 1.0.0
* Contact: alxminyaev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.alxminyaev.feature.chat.api.models


/**
 * 
 * @param id 
 * @param dateTime UTC
 * @param sender id of sender
 * @param receiver id of receiver
 * @param text 
 */
data class MessageResponse (
    val id: kotlin.Long,
    /* UTC */
    val dateTime: java.time.LocalDateTime,
    /* id of sender */
    val sender: kotlin.Long,
    /* id of receiver */
    val receiver: kotlin.Long,
    val text: kotlin.String? = null
) 

